### ISSUE TITLE
About pretrain results

### ISSUE THREAD

**Issue by Kanelankai** [RuotongWANG/TransVPR-model-implementation#3]
Thank you for your good work！
I used the adamw optimizer with 0.03 weight decay, 0.0001 initial learning rate with cosine learning rate decay schedule (I just set T_max=100 in pytorch optim.lr_scheduler.CosineAnnealingLR() function) as your paper said.
I trained my model with places365-standard, and the top1 accuracy on val dataset was only about 51%. 
I wonder if there are some mistakes with my parameter setting.
And whether any data augmentation method was used during your training.
Thanks a lot!

**Comment by kaiyi98** [comment]
> Thank you for your good work！ I used the adamw optimizer with 0.03 weight decay, 0.0001 initial learning rate with cosine learning rate decay schedule (I just set T_max=100 in pytorch optim.lr_scheduler.CosineAnnealingLR() function) as your paper said. I trained my model with places365-standard, and the top1 accuracy on val dataset was only about 51%. I wonder if there are some mistakes with my parameter setting. And whether any data augmentation method was used during your training. Thanks a lot!

Did you use the cross-entropy loss function?

**Comment by RuotongWANG** [comment]
Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
```
import math
def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
    if epoch < warmup:
        lr = lr / (warmup - epoch)
    else:
        lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr
```
The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion.
With this setting, the top1 accuracy on Places365 val set will be about 54.5%.
Hope this helps.

**Comment by Kanelankai** [comment]
> > Thank you for your good work！ I used the adamw optimizer with 0.03 weight decay, 0.0001 initial learning rate with cosine learning rate decay schedule (I just set T_max=100 in pytorch optim.lr_scheduler.CosineAnnealingLR() function) as your paper said. I trained my model with places365-standard, and the top1 accuracy on val dataset was only about 51%. I wonder if there are some mistakes with my parameter setting. And whether any data augmentation method was used during your training. Thanks a lot!
> 
> Did you use the cross-entropy loss function?

Yes. I used the cross entropy loss function. Besides, to further enhance model performance ,I also added mixup augmentation in a new training trial, but the training has not finished (Although I am not sure whether mixup will work with places365 dataset or not).

**Comment by Kanelankai** [comment]
> Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> 
> ```
> import math
> def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
>     if epoch < warmup:
>         lr = lr / (warmup - epoch)
>     else:
>         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
>     for param_group in optimizer.param_groups:
>         param_group['lr'] = lr
> ```
> 
> The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.

Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial  (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation)  This is probably the main reason with my lower accuracy. 
Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.

Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset?
Thank you again!

**Comment by kaiyi98** [comment]
> > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > ```
> > import math
> > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> >     if epoch < warmup:
> >         lr = lr / (warmup - epoch)
> >     else:
> >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> >     for param_group in optimizer.param_groups:
> >         param_group['lr'] = lr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> 
> Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> 
> Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!

I remember that the backbone network is frozen  when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. 
where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function

**Comment by Kanelankai** [comment]
> 



> > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > ```
> > > import math
> > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > >     if epoch < warmup:
> > >         lr = lr / (warmup - epoch)
> > >     else:
> > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > >     for param_group in optimizer.param_groups:
> > >         param_group['lr'] = lr
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > 
> > 
> > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> 
> I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function

Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found  someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).

**Comment by kaiyi98** [comment]
> > 
> 
> > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > ```
> > > > import math
> > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > >     if epoch < warmup:
> > > >         lr = lr / (warmup - epoch)
> > > >     else:
> > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > >     for param_group in optimizer.param_groups:
> > > >         param_group['lr'] = lr
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > 
> > > 
> > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > 
> > 
> > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> 
> Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).

thank you very much! I can use pan.baidu.com, thanks for your sharing.

**Comment by Kanelankai** [comment]
> > > 
> > 
> > 
> > > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > > ```
> > > > > import math
> > > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > > >     if epoch < warmup:
> > > > >         lr = lr / (warmup - epoch)
> > > > >     else:
> > > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > > >     for param_group in optimizer.param_groups:
> > > > >         param_group['lr'] = lr
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > > 
> > > > 
> > > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > > 
> > > 
> > > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> > 
> > 
> > Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).
> 
> thank you very much! I can use pan.baidu.com, thanks for your sharing.

https://pan.baidu.com/s/1xFqy4h-p_nExZELmWwlaPA
code: joke
If you cannot open the link, please inform me.

**Comment by kaiyi98** [comment]
> 

sorry, the link cannot be opened

**Comment by kaiyi98** [comment]
> > > > 
> > > 
> > > 
> > > > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > > > ```
> > > > > > import math
> > > > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > > > >     if epoch < warmup:
> > > > > >         lr = lr / (warmup - epoch)
> > > > > >     else:
> > > > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > > > >     for param_group in optimizer.param_groups:
> > > > > >         param_group['lr'] = lr
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > > > 
> > > > > 
> > > > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > > > 
> > > > 
> > > > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> > > 
> > > 
> > > Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).
> > 
> > 
> > thank you very much! I can use pan.baidu.com, thanks for your sharing.
> 
> https://pan.baidu.com/s/1xFqy4h-p_nExZELmWwlaPA code: joke If you cannot open the link, please inform me.

sorry, the link cannot be opened

**Comment by Kanelankai** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > > > > ```
> > > > > > > import math
> > > > > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > > > > >     if epoch < warmup:
> > > > > > >         lr = lr / (warmup - epoch)
> > > > > > >     else:
> > > > > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > > > > >     for param_group in optimizer.param_groups:
> > > > > > >         param_group['lr'] = lr
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > > > > 
> > > > > > 
> > > > > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > > > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > > > > 
> > > > > 
> > > > > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> > > > 
> > > > 
> > > > Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).
> > > 
> > > 
> > > thank you very much! I can use pan.baidu.com, thanks for your sharing.
> > 
> > 
> 
> sorry, the link cannot be opened

ok。我是从一个公众号上拿到的链接，你可以微信关注下“墨理学AI”，然后给公众号发消息“20210204”（不含引号），他就会把链接发给你了。
可以试下，祝好运

**Comment by kaiyi98** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > > > > > ```
> > > > > > > > import math
> > > > > > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > > > > > >     if epoch < warmup:
> > > > > > > >         lr = lr / (warmup - epoch)
> > > > > > > >     else:
> > > > > > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > > > > > >     for param_group in optimizer.param_groups:
> > > > > > > >         param_group['lr'] = lr
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > >     
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >     
> > > > > > > >   
> > > > > > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > > > > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > > > > > 
> > > > > > 
> > > > > > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> > > > > 
> > > > > 
> > > > > Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).
> > > > 
> > > > 
> > > > thank you very much! I can use pan.baidu.com, thanks for your sharing.
> > 
> > 
> > sorry, the link cannot be opened
> 
> ok。我是从一个公众号上拿到的链接，你可以微信关注下“墨理学AI”，然后给公众号发消息“20210204”（不含引号），他就会把链接发给你了。 可以试下，祝

> > > > > > 
> > > > > 
> > > > > 
> > > > > > > > Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> > > > > > > > ```
> > > > > > > > import math
> > > > > > > > def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
> > > > > > > >     if epoch < warmup:
> > > > > > > >         lr = lr / (warmup - epoch)
> > > > > > > >     else:
> > > > > > > >         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
> > > > > > > >     for param_group in optimizer.param_groups:
> > > > > > > >         param_group['lr'] = lr
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > >     
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >       
> > > > > > > >     
> > > > > > > > 
> > > > > > > >     
> > > > > > > >   
> > > > > > > > The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.
> > > > > > > 
> > > > > > > 
> > > > > > > Thank you very much for the reply. I did several trials of model training with different settings. I forgot that I did not use data augmentation in the reported training trial (accuracy = 51.84% exactly. Other trials reported poorer performance due to some code bugs with data augmentation) This is probably the main reason with my lower accuracy. Maybe lr is also a reason since I did not add a warmup procedure. I will re-train the network with the lr code you shared.
> > > > > > > Sorry about another question, did you freeze the backbone network when pre-training the attention and dimensionality reduction layers on MSLS dataset? Thank you again!
> > > > > > 
> > > > > > 
> > > > > > I remember that the backbone network is frozen when pre-training the attention and dimensionality reduction layers on MSLS dataset in the paper 3.4.Training Strategy. where did you download the place365 dataset? I visited the website but it shows '404 not found'. Thank you for answering my question about the loss function
> > > > > 
> > > > > 
> > > > > Thank you for your reply. I also visited the official site of places-365 and found the dataset is under maintenance. Finally, I found someone uploaded places365-standard dataset to pan.baidu.com. If you can use pan.baidu.com, I will share you the link (The download will be slow if you do not have a membership).
> > > > 
> > > > 
> > > > thank you very much! I can use pan.baidu.com, thanks for your sharing.
> > 
> > 
> > sorry, the link cannot be opened
> 
> ok。我是从一个公众号上拿到的链接，你可以微信关注下“墨理学AI”，然后给公众号发消息“20210204”（不含引号），他就会把链接发给你了。 可以试下，祝好运

Thanks very much！I have downloaded the dataset, but the data for the validation and test sets does not seem to have label.

**Comment by Kanelankai** [comment]
You could download the validation set from this link.
https://www.heywhale.com/mw/dataset/5f1fe90ed278b1002c20b078/file
Sorry that I did not download the validation and test set from pan.baidu.com because I obtained the validation data from here at first. @kaiyi98

**Comment by kaiyi98** [comment]
> 

Great！Thanks， and I had started training the model on 2 NVIDIA GeForce RTX 3090 GPUs. It looks like it will take a lot of time. How long do you take to train model for 100 epochs?

**Comment by kaiyi98** [comment]
> You could download the validation set from this link. https://www.heywhale.com/mw/dataset/5f1fe90ed278b1002c20b078/file Sorry that I did not download the validation and test set from pan.baidu.com because I obtained the validation data from here at first. @kaiyi98

Great！Thanks， and I had started training the model on 2 NVIDIA GeForce RTX 3090 GPUs. It looks like it will take a lot of time. How long do you take to train model for 100 epochs?

**Comment by Kanelankai** [comment]
> > You could download the validation set from this link. https://www.heywhale.com/mw/dataset/5f1fe90ed278b1002c20b078/file Sorry that I did not download the validation and test set from pan.baidu.com because I obtained the validation data from here at first. @kaiyi98
> 
> Great！Thanks， and I had started training the model on 2 NVIDIA GeForce RTX 3090 GPUs. It looks like it will take a lot of time. How long do you take to train model for 100 epochs?

I am training the model on 2 Tesla V100-SXM2 GPUs. It takes about 1.4h for one epoch.
The training procedure is still ongoing with the 88th epoch. At present, the best val_acc reaches about 54.8%. 
By the way, have you finished the training code on MSLS dataset? I borrowed the training code from Patch-Netvlad, and tried to fine-tune a pretrained model, but the result was not very satisfactory.

**Comment by kaiyi98** [comment]
> Tesla V100-SXM2



> > > You could download the validation set from this link. https://www.heywhale.com/mw/dataset/5f1fe90ed278b1002c20b078/file Sorry that I did not download the validation and test set from pan.baidu.com because I obtained the validation data from here at first. @kaiyi98
> > 
> > 
> > Great！Thanks， and I had started training the model on 2 NVIDIA GeForce RTX 3090 GPUs. It looks like it will take a lot of time. How long do you take to train model for 100 epochs?
> 
> I am training the model on 2 Tesla V100-SXM2 GPUs. It takes about 1.4h for one epoch. The training procedure is still ongoing with the 88th epoch. At present, the best val_acc reaches about 54.8%. By the way, have you finished the training code on MSLS dataset? I borrowed the training code from Patch-Netvlad, and tried to fine-tune a pretrained model, but the result was not very satisfactory.

I haven't started the second part of training code on MSLS. The code of Patch-Netvlad provide the 'class MSLS' that can be referenced possibly. I will try my best to complete the second training code，and we can have more communication by email or others If you wish.

**Comment by kaiyi98** [comment]
> > > You could download the validation set from this link. https://www.heywhale.com/mw/dataset/5f1fe90ed278b1002c20b078/file Sorry that I did not download the validation and test set from pan.baidu.com because I obtained the validation data from here at first. @kaiyi98
> > 
> > 
> > Great！Thanks， and I had started training the model on 2 NVIDIA GeForce RTX 3090 GPUs. It looks like it will take a lot of time. How long do you take to train model for 100 epochs?
> 
> I am training the model on 2 Tesla V100-SXM2 GPUs. It takes about 1.4h for one epoch. The training procedure is still ongoing with the 88th epoch. At present, the best val_acc reaches about 54.8%. By the way, have you finished the training code on MSLS dataset? I borrowed the training code from Patch-Netvlad, and tried to fine-tune a pretrained model, but the result was not very satisfactory.

I haven't started the second part of training code on MSLS. The code of Patch-Netvlad provide the 'class MSLS' that can be referenced possibly. I will try my best to complete the second training code in this week，and we can have more communication by email or others If you wish.

**Comment by Kanelankai** [comment]
> Hi, thanks for your interest. Your parameter settings seem to be all correct. The only thing is that we didn't use pytorch `optim.lr_scheduler.CosineAnnealingLR()` function and use the lr adjust function bellow:
> 
> ```
> import math
> def adjust_learning_rate(optimizer, epoch, lr, all_epochs=100, warmup=5):
>     if epoch < warmup:
>         lr = lr / (warmup - epoch)
>     else:
>         lr *= 0.5 * (1. + math.cos(math.pi * (epoch - warmup) / (all_epochs - warmup)))
>     for param_group in optimizer.param_groups:
>         param_group['lr'] = lr
> ```
> 
> The pytorch data augmentation functions `RandomResizedCrop(224)` and `RandomHorizontalFlip()` are used. And the input images are normalized by mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]. The cross-entropy loss function is used as training criterion. With this setting, the top1 accuracy on Places365 val set will be about 54.5%. Hope this helps.


@RuotongWANG Thank you very much for the information about parameter setting and lr adjustment schedule for pre-training the backbone.I have finished the backbone pretraining and the val accuracy reached about 55.2%.

So I went on with the attention layer and dimensionality reduction layer pretraining as the paper said, using the code from patch netvlad with some little modification.(I have tested your model with the code and it obtained almost the same results with global feature in Fig. 4 of paper.)
I set the warmup epoch number equals 0 with your lr adjustment function (initial learning rate is 0.0003), freezing the backbone part. After training for 5 epochs, the results are shown as follows:
![Screenshot from 2022-08-02 09-39-01](https://user-images.githubusercontent.com/25300063/182274096-1b3a1c8c-1576-4d12-9a4d-95b8a709dbd9.png)

Besides, I used the best pretrained model to train on MSLS. The training is now going on with the 3rd epoch without warmup. But the Recall on val dataset are very low(Recall@1 is only 0.1 at present), and the training loss for many iterations is 0.000 (see the fig beloww). I'm not quite sure whether it is correct or not. Could you please help me to figure out where the problem is? 
Thank you in advance. 
![Screenshot from 2022-08-02 09-55-31](https://user-images.githubusercontent.com/25300063/182275400-86ed211f-7bcc-4f9d-8bad-3cfc64d0fd49.png)
