### ISSUE TITLE
RunTimeError while running inference on custom dataset

### ISSUE THREAD

**Issue by divyagupta25** [RuotongWANG/TransVPR-model-implementation#5]
Hi, 
Thank you for sharing your work with the community! 
I am trying to run inference (using the model pre-trained on Pitts30k), on a custom dataset which has 2500 query and index images. I am getting a run time error on the line - https://github.com/RuotongWANG/TransVPR-model-implementation/blob/7d7601f4dd96f522872810fb1b69813ec56e1ab0/test_msls.py#L61

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

The dimension of mask 1 is torch.Size([1200]) and mask 2 is torch.Size([100, 1200]). Could you please tell if this is expected or not?

**Comment by RuotongWANG** [comment]
hi, little bug fixed
