### ISSUE TITLE
Train TransVPR

### ISSUE THREAD

**Issue by libenchong** [RuotongWANG/TransVPR-model-implementation#8]
Hello, when training TransVPR code, I used the PatchNetVLAD process, which changed the model code to TransVPR, the optimizer to AdamW, and loaded the weight you provided. But I found that after an epoch training, the effect became very poor. I want to ask if you use the data loading method of PatchNetVLAD

**Comment by Kaacoinnn** [comment]
hello，can i have your training code with PatchNetVLAD process？
